### ISSUE TITLE
File APi's deprecated

### ISSUE THREAD

**Issue by ymohii** [Khan/appengine-mapreduce#4]
according to google file api's are going to be shutdown.  https://cloud.google.com/appengine/docs/deprecations/files_api 
I can see that there is still some parts in the source code depending on it. 
https://github.com/Khan/appengine-mapreduce/search?utf8=%E2%9C%93&q=google.appengine.api.files&type=Code

**Comment by MattFaus** [comment]
Thanks for posting. We are aware of the Files API deprecation and have an internal task to migrate the few existing places that use it to the GCS client.

**Comment by ymohii** [comment]
@MattFaus 
Thank you for your effort in this issue, I know you closed it but we are depending on your fork for some technical reasons, so do you have any deadlines for your internal task.

**Comment by MattFaus** [comment]
@ymohii Yes, we've completed this internal task, sorry for not updating here. Since Google has the mapreduce library in github we decided to rebase our fork off of that which can be found here: https://github.com/Khan/appengine-mapreduce-1

It has been running in production for a few weeks now, so it should fill all of your needs. We also submitted several of our patches upstream and they have been accepted, so you could just fork from there for a more up-to-date branch.

**Comment by ymohii** [comment]
@MattFaus 
thanks a lot for your feedback and effort guys :)
